#!/bin/sh

RELEASE=/var/www/wordpicker/

echo 'Copying Python files..'
cp -u *.py $RELEASE
echo 'Copying sh files..'
cp -u *.sh $RELEASE
echo 'Copying Makefile..'
cp -u Makefile $RELEASE
echo 'Copying xml files..'
cp -u *.xml $RELEASE
echo 'Copying cron files..'
cp -u *.cron $RELEASE
echo 'Copying templates directory..'
cp -ru templates $RELEASE
echo 'Copying static directory..'
cp -ru static $RELEASE
echo 'Copying venv directory..'
cp -ru venv $RELEASE
